In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% ! important;}
div.cell.code_cell.rendered{width:100%}
div.input_prompt{padding:0px}
div.CodeMirror {font-family:Consolas ; font-size:12pt;}
div.text_cell_render.rendered_html {font-size:12pt;}
div.output {font-size:12pt; font-weight:bold}
div.input {font-family:Consolas ; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper {padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

# 1. tensorflow v2.xx 에서 v1 사용하기

In [3]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() # tensorflow v2 비활성화하고 v1 활성화
import pandas as pd
import numpy as np

Instructions for updating:
non-resource variables are not supported in the long term


## Tensorflow
- 데이터 흐름 그래프(tensor 객체의 흐름)을 사용하는 수치 계산 라이브러리
- 그래프는 node(연산)와 edge로 구성
- sess = tf.Session()을 이용해서 실행 환경
- sess.run()을 통해서 실행 결과를 확인

In [5]:
# 1단계 : tensor(상수 노드 하나) 정의
node1 = tf.constant('Hello,Tenserflow')
# 2단계 : 세션(연산을 실행하는 환경)생성
sess = tf.Session()
# 3단계 : 실제 실행 및 출력
print(sess.run(node1))
print(sess.run(node1).decode())

b'Hello,Tenserflow'
Hello,Tenserflow


In [8]:
# 간단한 연산 tensor 그래프
# 1. 그래프 정의
node1 = tf.constant(10, dtype=tf.float16)
node2 = tf.constant(20, dtype=tf.float16)
node3 = tf.add(node1, node2)
# 2. 세션생성
sess = tf.Session()
# 3. 세션실행 & 결과
print(sess.run([node1, node2, node3]))

[10.0, 20.0, 30.0]


In [9]:
# 타입변경
node1 = tf.constant(np.array([1,2,3]), dtype=tf.int16)
node2 = tf.cast(node1, dtype=tf.float32)
sess = tf.Session()
print(sess.run([node1,node2]))

[array([1, 2, 3], dtype=int16), array([1., 2., 3.], dtype=float32)]


In [12]:
# 평균값 계산 : tf.reduce_mean()
data = np.array([1.,2.,3.,4.]) # 데이터가 정수로 들어오면 정수로 계산
m = tf.reduce_mean(data)
sess=tf.Session()
print(sess.run(m))

2.5


In [13]:
# tf.random_nomal([size]) : 평균이 0이고 표준편차가 1인 난수 size개 발생
w=tf.random_normal([1])
seee = tf.Session()
sess.run(w)

array([1.6910446], dtype=float32)

In [14]:
# 변수 노드
x = tf.Variable(tf.random_normal([1]))
sess = tf.Session()
sess.run(tf.global_variables_initializer()) # 변수 초기화
sess.run(w)

array([2.0097313], dtype=float32)

# 2. tensorflow v1을 이용한 회귀분석 구현
## 2.1 독립변수 x가 1개, 타겟(종속)변수 y가 1개

In [15]:
# tensor 그래프 정의
# 데이터 셋 확보
x = np.array([1,2,3])
y = np.array([2,3,4])
# weight와 bias
W = tf.Variable(tf.random.normal([1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')
# Hat, Hypothesis결과는 numpy배열
H = W*x+b
# cost function(손실함수 : mse)
cost = tf.reduce_mean(tf.square(H-y))
'''
학습목적 : cost가 최소가 되는 W,b를 찾는 것
cost 함수는 2차함수이므로 곡선 그래프. 접선의 미분값이 0이 되는 방향
(경사하강법GradienDescent) 
'''
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
# 세션 생성
sess = tf.Session()
# W,b 초기화
sess.run(tf.global_variables_initializer())
# 6000번 학습(v2 에서의 fit함수)
for step in range(6001):
    _, cost_val, W_val, b_val = sess.run([train, cost, W, b])
    if step%300==0:
        print(f'{step}번째 cost:{cost_val},w:{W_val},b:{b_val}')

0번째 cost:24.443742752075195,w:[-0.5196012],b:[-0.17830837]
300번째 cost:0.00620655482634902,w:[1.09128],b:[0.792499]
600번째 cost:0.00146449264138937,w:[1.0443399],b:[0.8992051]
900번째 cost:0.0003455646801739931,w:[1.0215386],b:[0.95103794]
1200번째 cost:8.153796807164326e-05,w:[1.0104624],b:[0.97621655]
1500번째 cost:1.924049502122216e-05,w:[1.0050822],b:[0.9884468]
1800번째 cost:4.540519967122236e-06,w:[1.002469],b:[0.99438775]
2100번째 cost:1.0716595397752826e-06,w:[1.0011996],b:[0.9972733]
2400번째 cost:2.5337172360195837e-07,w:[1.0005834],b:[0.9986743]
2700번째 cost:6.01374168240909e-08,w:[1.0002841],b:[0.9993542]
3000번째 cost:1.4340044707239485e-08,w:[1.0001386],b:[0.9996846]
3300번째 cost:3.4175873242503485e-09,w:[1.000068],b:[0.999846]
3600번째 cost:8.25388923875181e-10,w:[1.0000331],b:[0.9999242]
3900번째 cost:2.0211625428867563e-10,w:[1.0000166],b:[0.9999626]
4200번째 cost:5.550286272248961e-11,w:[1.000009],b:[0.9999805]
4500번째 cost:5.328478283606053e-11,w:[1.0000087],b:[0.9999811]
4800번째 cost:5.32847

In [18]:
# 최종적으로 나온 회귀식 H=W*x+b
W_, b_ = sess.run([W,b])

In [19]:
def predict(x):
    return W_[0]* x + b_[0]

In [20]:
predict(5)

6.000024616718292

## 2.2 predict을 위한 placeholder 이용
- placeholder : 외부에서 데이터를 입력받을 수 있는 노드

In [23]:
x = tf.placeholder(dtype=tf.float32)
H = 1*x + 1
sess = tf.Session()
sess.run([x,H], feed_dict={x:np.array([40,50])})

[array([40., 50.], dtype=float32), array([41., 51.], dtype=float32)]

In [25]:
# tensor 그래프 정의
# 데이터 셋 확보
x_data = np.array([1,2,3])
y_data = np.array([2,3,4])
# placeholder 설정(x,y)
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)
# weight와 bias
W = tf.Variable(tf.random.normal([1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')
# Hat, Hypothesis결과는 numpy배열
H = W*x+b
# cost function(손실함수 : mse)
cost = tf.reduce_mean(tf.square(H-y))
'''
학습목적 : cost가 최소가 되는 W,b를 찾는 것
cost 함수는 2차함수이므로 곡선 그래프. 접선의 미분값이 0이 되는 방향
(경사하강법GradienDescent) 
'''
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
# 세션 생성
sess = tf.Session()
# W,b 초기화
sess.run(tf.global_variables_initializer())
# 6000번 학습(v2 에서의 fit함수)
for step in range(6001):
    _, cost_val, W_val, b_val = sess.run([train, cost, W, b],
                                        feed_dict={x:x_data,
                                                  y:y_data})
    if step%300==0:
        print(f'{step}번째 cost:{cost_val},w:{W_val},b:{b_val}')

0번째 cost:13.738765716552734,w:[0.1112799],b:[-0.44064015]
300번째 cost:0.026309633627533913,w:[1.1879352],b:[0.57277906]
600번째 cost:0.006208028644323349,w:[1.091291],b:[0.79247427]
900번째 cost:0.0014648367650806904,w:[1.0443451],b:[0.89919317]
1200번째 cost:0.0003456456179264933,w:[1.0215411],b:[0.9510322]
1500번째 cost:8.155623800121248e-05,w:[1.0104637],b:[0.9762137]
1800번째 cost:1.924347634485457e-05,w:[1.0050827],b:[0.98844564]
2100번째 cost:4.541298494586954e-06,w:[1.0024692],b:[0.99438715]
2400번째 cost:1.072059149009874e-06,w:[1.0011997],b:[0.99727315]
2700번째 cost:2.5332309405712294e-07,w:[1.0005834],b:[0.9986742]
3000번째 cost:6.006644071021583e-08,w:[1.000284],b:[0.9993544]
3300번째 cost:1.4351542176882504e-08,w:[1.0001386],b:[0.9996847]
3600번째 cost:3.4121967473765835e-09,w:[1.000068],b:[0.999846]
3900번째 cost:8.193978828785475e-10,w:[1.0000331],b:[0.9999243]
4200번째 cost:2.0012673462854735e-10,w:[1.0000167],b:[0.9999626]
4500번째 cost:5.635077474086536e-11,w:[1.000009],b:[0.99998045]
4800번째 cost

In [26]:
# 예측하기
sess.run(H, feed_dict={x:7})

array([8.000041], dtype=float32)

## 2.3 scale이 다른 데이터들의 회귀분석 구현(scale 조정X)

In [27]:
x_data = np.array([1, 2, 5, 8, 10])
y_data = np.array([5, 15, 68, 80, 95])
# placeholder 설정
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)
W = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.random_normal([1]))
# Hypothesis
H= W*x + b
# cost (손실힘수 - 이차함수)
cost = (tf.reduce_mean(tf.square(H-y)))
# 경사하강법
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train=optimizer.minimize(cost)
# Session & 변수 초기화
sess=tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(1,6001):
    _, cost_val, = sess.run([train,cost], feed_dict={x:x_data, y:y_data})
    if step%300==0:
        print("{}/6000번째 cost:{}".format(step+1, cost_val))

301/6000번째 cost:79.15477752685547
601/6000번째 cost:79.139892578125
901/6000번째 cost:79.13946533203125
1201/6000번째 cost:79.13948059082031
1501/6000번째 cost:79.13945007324219
1801/6000번째 cost:79.13946533203125
2101/6000번째 cost:79.13944244384766
2401/6000번째 cost:79.13946533203125
2701/6000번째 cost:79.13946533203125
3001/6000번째 cost:79.13946533203125
3301/6000번째 cost:79.13946533203125
3601/6000번째 cost:79.13946533203125
3901/6000번째 cost:79.13946533203125
4201/6000번째 cost:79.13946533203125
4501/6000번째 cost:79.13946533203125
4801/6000번째 cost:79.13946533203125
5101/6000번째 cost:79.13946533203125
5401/6000번째 cost:79.13946533203125
5701/6000번째 cost:79.13946533203125
6001/6000번째 cost:79.13946533203125


## 2.4 scale이 다른 데이터들의 회귀분석 구현(scale 조정O)
### scale 조정방법 : 모든 데이터를 일정범위내로 조정
- normalization(정규화) : 모든 데이터를 0~1 사이로 조정
                         X - Xmin
   normalization =   ───────────────────          
                        Xmax - Xmin
                        
           * 위의 식을 써도 되지만 라이브러리(sklearn.preprocessing.MinMaxScaler)를 주로 씀
           
- standarization(표준화) : 데이터의 평균을 0, 표준편차를 1로 조정
                       
                         X - Xmean
    standaization =  ─────────────────────
                        Xstd(표준편차)
                        
           * 라이브러리를 더 추천(sklearn.preprocessing.StandardScaler)

In [29]:
# 라이브러리 쓰지 않고 정규화
x_data = np.array([1, 2, 5, 8, 10])
y_data = np.array([5, 15, 68, 80, 95])
norm_scaled_x_data = (x_data - x_data.min())/(x_data.max() - x_data.min())
norm_scaled_y_data = (y_data - y_data.min())/(y_data.max() - y_data.min())

array([0.        , 0.11111111, 0.7       , 0.83333333, 1.        ])

In [34]:
# 라이브러리를 사용하여 정규화
x_data = np.array([1, 2, 5, 8, 10]).reshape(-1,1)
y_data = np.array([5, 15, 68, 80, 95]).reshape(-1,1)
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler() # 독립변수 x를 정규화 시킬 객체
scaler_x.fit(x_data)
norm_scaled_x_data = scaler_x.fit_transform(x_data)
scaler_y=MinMaxScaler() # 종속(타겟)변수 y를 정규화시킬 객체
norm_scaled_y_data = scaler_y.fit_transform(y_data)
norm_scaled_y_data

array([[0.        ],
       [0.11111111],
       [0.7       ],
       [0.83333333],
       [1.        ]])

In [39]:
# 라이브러리 쓰지않고 표준화
x_data = np.array([1, 2, 5, 8, 10])
y_data = np.array([5, 15, 68, 80, 95])
stan_scaled_x_data = (x_data - x_data.mean()) / x_data.std()
stan_scaled_y_data = (y_data - y_data.mean()) / y_data.std()
np.column_stack([x_data, norm_scaled_x_data, stan_scaled_x_data])

array([[ 1.        ,  0.        , -1.22474487],
       [ 2.        ,  0.11111111, -0.93313895],
       [ 5.        ,  0.44444444, -0.05832118],
       [ 8.        ,  0.77777778,  0.81649658],
       [10.        ,  1.        ,  1.39970842]])

In [40]:
np.column_stack([y_data, norm_scaled_y_data, stan_scaled_y_data])

array([[ 5.        ,  0.        , -1.32373476],
       [15.        ,  0.11111111, -1.04563922],
       [68.        ,  0.7       ,  0.42826713],
       [80.        ,  0.83333333,  0.76198177],
       [95.        ,  1.        ,  1.17912508]])

In [46]:
# 라이브러리를 사용하여 표준화
x_data = np.array([1, 2, 5, 8, 10]).reshape(-1,1)
y_data = np.array([5, 15, 68, 80, 95]).reshape(-1,1)

from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
stan_scaler_x_data = scaler_x.fit_transform(x_data)
scaler_y = StandardScaler()
stan_scaler_y_data = scaler_y.fit_transform(y_data)

array([[-1.32373476],
       [-1.04563922],
       [ 0.42826713],
       [ 0.76198177],
       [ 1.17912508]])

In [47]:
# 스케일 조정된 데이터를 다시 복구
scaler_y.inverse_transform(stan_scaler_y_data)

array([[ 5.],
       [15.],
       [68.],
       [80.],
       [95.]])

In [51]:
x_data = np.array([1, 2, 5, 8, 10])
y_data = np.array([5, 15, 68, 80, 95])
# placeholder 설정
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)
W = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.random_normal([1]))
# Hypothesis
H= W*x + b
# cost (손실힘수 - 이차함수)
cost = (tf.reduce_mean(tf.square(H-y)))
# 경사하강법
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train=optimizer.minimize(cost)
# Session & 변수 초기화
sess=tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(1,6001):
    _, cost_val, = sess.run([train,cost], feed_dict={x:norm_scaled_x_data, 
                                                     y:norm_scaled_y_data})
    if step%300==0:
        print("{}/6000번째 cost:{}".format(step, cost_val))

300/6000번째 cost:0.13457641005516052
600/6000번째 cost:0.040567509829998016
900/6000번째 cost:0.01736985519528389
1200/6000번째 cost:0.011645564809441566
1500/6000번째 cost:0.010233039036393166
1800/6000번째 cost:0.009884487837553024
2100/6000번째 cost:0.009798477403819561
2400/6000번째 cost:0.009777255356311798
2700/6000번째 cost:0.009772013872861862
3000/6000번째 cost:0.009770723059773445
3300/6000번째 cost:0.009770408272743225
3600/6000번째 cost:0.009770330041646957
3900/6000번째 cost:0.009770307689905167
4200/6000번째 cost:0.009770306758582592
4500/6000번째 cost:0.009770303033292294
4800/6000번째 cost:0.00977030023932457
5100/6000번째 cost:0.009770303964614868
5400/6000번째 cost:0.009770302101969719
5700/6000번째 cost:0.009770302101969719
6000/6000번째 cost:0.009770302101969719
